//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAPI_Interviewer.Languages {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TAPI_Interviewer.Languages.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   로그아웃과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string code0 {
            get {
                return ResourceManager.GetString("code0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설문지를 선택해 주세요. (아래 설문제목을 터치해 주세요.)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string code1 {
            get {
                return ResourceManager.GetString("code1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   진행상황 보기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string code10 {
            get {
                return ResourceManager.GetString("code10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   참여자 이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string code11 {
            get {
                return ResourceManager.GetString("code11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   참여상태과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string code12 {
            get {
                return ResourceManager.GetString("code12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설문 이어하기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string code13 {
            get {
                return ResourceManager.GetString("code13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   응답자 성명을 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string code14 {
            get {
                return ResourceManager.GetString("code14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   동명이인이 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string code15 {
            get {
                return ResourceManager.GetString("code15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선정탈락과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string code16 {
            get {
                return ResourceManager.GetString("code16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   쿼터오버과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string code17 {
            get {
                return ResourceManager.GetString("code17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   진행중과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string code18 {
            get {
                return ResourceManager.GetString("code18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string code19 {
            get {
                return ResourceManager.GetString("code19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설문참여하기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string code2 {
            get {
                return ResourceManager.GetString("code2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용안함과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string code20 {
            get {
                return ResourceManager.GetString("code20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string code21 {
            get {
                return ResourceManager.GetString("code21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설문이어하기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string code22 {
            get {
                return ResourceManager.GetString("code22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   응답자성명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string code3 {
            get {
                return ResourceManager.GetString("code3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설문참여하기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string code4 {
            get {
                return ResourceManager.GetString("code4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   응답자 설명에 중복된 이름을 넣을 수 없습니다. 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string code5 {
            get {
                return ResourceManager.GetString("code5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   동명이인일 경우 뒤에 숫자를 붙여서 입력해주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string code5_1 {
            get {
                return ResourceManager.GetString("code5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   예시) &apos;홍길동&apos;이 이미 있는 경우 -&gt; &apos;홍길동1&apos; , &apos;홍길동2&apos;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string code5_2 {
            get {
                return ResourceManager.GetString("code5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   진행상황과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string code6 {
            get {
                return ResourceManager.GetString("code6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string code7 {
            get {
                return ResourceManager.GetString("code7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   진행과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string code8 {
            get {
                return ResourceManager.GetString("code8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   부과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string code9 {
            get {
                return ResourceManager.GetString("code9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
    }
}
