#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAPI_Interviewer.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SURVEYTOOL")]
	public partial class SURVEYTOOLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 확장성 메서드 정의
    partial void OnCreated();
    partial void InsertT_Interviewer(T_Interviewer instance);
    partial void UpdateT_Interviewer(T_Interviewer instance);
    partial void DeleteT_Interviewer(T_Interviewer instance);
    partial void InsertT_Script(T_Script instance);
    partial void UpdateT_Script(T_Script instance);
    partial void DeleteT_Script(T_Script instance);
    partial void InsertT_InterviewerLoginInfo(T_InterviewerLoginInfo instance);
    partial void UpdateT_InterviewerLoginInfo(T_InterviewerLoginInfo instance);
    partial void DeleteT_InterviewerLoginInfo(T_InterviewerLoginInfo instance);
    partial void InsertT_Questionnaire(T_Questionnaire instance);
    partial void UpdateT_Questionnaire(T_Questionnaire instance);
    partial void DeleteT_Questionnaire(T_Questionnaire instance);
    partial void InsertT_QuestionnaireDistribution(T_QuestionnaireDistribution instance);
    partial void UpdateT_QuestionnaireDistribution(T_QuestionnaireDistribution instance);
    partial void DeleteT_QuestionnaireDistribution(T_QuestionnaireDistribution instance);
    partial void InsertT_Quota(T_Quota instance);
    partial void UpdateT_Quota(T_Quota instance);
    partial void DeleteT_Quota(T_Quota instance);
    #endregion
		
		public SURVEYTOOLDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SURVEYTOOLConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SURVEYTOOLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SURVEYTOOLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SURVEYTOOLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SURVEYTOOLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<T_Interviewer> T_Interviewers
		{
			get
			{
				return this.GetTable<T_Interviewer>();
			}
		}
		
		public System.Data.Linq.Table<T_Script> T_Scripts
		{
			get
			{
				return this.GetTable<T_Script>();
			}
		}
		
		public System.Data.Linq.Table<T_InterviewerLoginInfo> T_InterviewerLoginInfos
		{
			get
			{
				return this.GetTable<T_InterviewerLoginInfo>();
			}
		}
		
		public System.Data.Linq.Table<T_Questionnaire> T_Questionnaires
		{
			get
			{
				return this.GetTable<T_Questionnaire>();
			}
		}
		
		public System.Data.Linq.Table<T_EmployeeInfo> T_EmployeeInfo
		{
			get
			{
				return this.GetTable<T_EmployeeInfo>();
			}
		}
		
		public System.Data.Linq.Table<T_QuestionnaireDistribution> T_QuestionnaireDistribution
		{
			get
			{
				return this.GetTable<T_QuestionnaireDistribution>();
			}
		}
		
		public System.Data.Linq.Table<T_Quota> T_Quota
		{
			get
			{
				return this.GetTable<T_Quota>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GET_RPS_LIVE_T_Employee")]
		public int GET_RPS_LIVE_T_Employee()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GET_InterviewerInfo")]
		public ISingleResult<GET_InterviewerInfoResult> GET_InterviewerInfo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> questionnaireID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), questionnaireID);
			return ((ISingleResult<GET_InterviewerInfoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GET_RPS_LIVE_T_Interviewer")]
		public int GET_RPS_LIVE_T_Interviewer()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GET_TAPIProject")]
		public ISingleResult<GET_TAPIProjectResult> GET_TAPIProject([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string employeeNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> isGang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string etc1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string etc2)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), employeeNumber, isGang, etc1, etc2);
			return ((ISingleResult<GET_TAPIProjectResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Interviewer")]
	public partial class T_Interviewer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id;
		
		private System.Nullable<decimal> _employeeNumber;
		
		private string _userName;
		
		private string _rrnFront;
		
		private string _homePhoneNumber;
		
		private string _mobilePhoneNumber;
		
		private short _deleteYN;
		
		private System.DateTime _createDateTime;
		
		private System.DateTime _updateDateTime;
		
    #region 확장성 메서드 정의
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(decimal value);
    partial void OnidChanged();
    partial void OnemployeeNumberChanging(System.Nullable<decimal> value);
    partial void OnemployeeNumberChanged();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnrrnFrontChanging(string value);
    partial void OnrrnFrontChanged();
    partial void OnhomePhoneNumberChanging(string value);
    partial void OnhomePhoneNumberChanged();
    partial void OnmobilePhoneNumberChanging(string value);
    partial void OnmobilePhoneNumberChanged();
    partial void OndeleteYNChanging(short value);
    partial void OndeleteYNChanged();
    partial void OncreateDateTimeChanging(System.DateTime value);
    partial void OncreateDateTimeChanged();
    partial void OnupdateDateTimeChanging(System.DateTime value);
    partial void OnupdateDateTimeChanged();
    #endregion
		
		public T_Interviewer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(38,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employeeNumber", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> employeeNumber
		{
			get
			{
				return this._employeeNumber;
			}
			set
			{
				if ((this._employeeNumber != value))
				{
					this.OnemployeeNumberChanging(value);
					this.SendPropertyChanging();
					this._employeeNumber = value;
					this.SendPropertyChanged("employeeNumber");
					this.OnemployeeNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="VarChar(100)")]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this.OnuserNameChanging(value);
					this.SendPropertyChanging();
					this._userName = value;
					this.SendPropertyChanged("userName");
					this.OnuserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rrnFront", DbType="VarChar(20)")]
		public string rrnFront
		{
			get
			{
				return this._rrnFront;
			}
			set
			{
				if ((this._rrnFront != value))
				{
					this.OnrrnFrontChanging(value);
					this.SendPropertyChanging();
					this._rrnFront = value;
					this.SendPropertyChanged("rrnFront");
					this.OnrrnFrontChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_homePhoneNumber", DbType="VarChar(30)")]
		public string homePhoneNumber
		{
			get
			{
				return this._homePhoneNumber;
			}
			set
			{
				if ((this._homePhoneNumber != value))
				{
					this.OnhomePhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._homePhoneNumber = value;
					this.SendPropertyChanged("homePhoneNumber");
					this.OnhomePhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobilePhoneNumber", DbType="VarChar(30)")]
		public string mobilePhoneNumber
		{
			get
			{
				return this._mobilePhoneNumber;
			}
			set
			{
				if ((this._mobilePhoneNumber != value))
				{
					this.OnmobilePhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._mobilePhoneNumber = value;
					this.SendPropertyChanged("mobilePhoneNumber");
					this.OnmobilePhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleteYN", DbType="SmallInt NOT NULL")]
		public short deleteYN
		{
			get
			{
				return this._deleteYN;
			}
			set
			{
				if ((this._deleteYN != value))
				{
					this.OndeleteYNChanging(value);
					this.SendPropertyChanging();
					this._deleteYN = value;
					this.SendPropertyChanged("deleteYN");
					this.OndeleteYNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDateTime", DbType="DateTime NOT NULL")]
		public System.DateTime createDateTime
		{
			get
			{
				return this._createDateTime;
			}
			set
			{
				if ((this._createDateTime != value))
				{
					this.OncreateDateTimeChanging(value);
					this.SendPropertyChanging();
					this._createDateTime = value;
					this.SendPropertyChanged("createDateTime");
					this.OncreateDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updateDateTime", DbType="DateTime NOT NULL")]
		public System.DateTime updateDateTime
		{
			get
			{
				return this._updateDateTime;
			}
			set
			{
				if ((this._updateDateTime != value))
				{
					this.OnupdateDateTimeChanging(value);
					this.SendPropertyChanging();
					this._updateDateTime = value;
					this.SendPropertyChanged("updateDateTime");
					this.OnupdateDateTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Script")]
	public partial class T_Script : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id;
		
		private decimal _questionnaireID;
		
		private string _script;
		
		private System.Data.Linq.Binary _contents;
		
		private string _hashString;
		
		private System.DateTime _createDateTime;
		
		private System.Xml.Linq.XElement _variableList;
		
		private System.Xml.Linq.XElement _quotaVariableList;
		
		private System.Xml.Linq.XElement _quotaList;
		
		private System.Xml.Linq.XElement _rotationInfo;
		
		private System.Data.Linq.Binary _parser;
		
    #region 확장성 메서드 정의
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(decimal value);
    partial void OnidChanged();
    partial void OnquestionnaireIDChanging(decimal value);
    partial void OnquestionnaireIDChanged();
    partial void OnscriptChanging(string value);
    partial void OnscriptChanged();
    partial void OncontentsChanging(System.Data.Linq.Binary value);
    partial void OncontentsChanged();
    partial void OnhashStringChanging(string value);
    partial void OnhashStringChanged();
    partial void OncreateDateTimeChanging(System.DateTime value);
    partial void OncreateDateTimeChanged();
    partial void OnvariableListChanging(System.Xml.Linq.XElement value);
    partial void OnvariableListChanged();
    partial void OnquotaVariableListChanging(System.Xml.Linq.XElement value);
    partial void OnquotaVariableListChanged();
    partial void OnquotaListChanging(System.Xml.Linq.XElement value);
    partial void OnquotaListChanged();
    partial void OnrotationInfoChanging(System.Xml.Linq.XElement value);
    partial void OnrotationInfoChanged();
    partial void OnparserChanging(System.Data.Linq.Binary value);
    partial void OnparserChanged();
    #endregion
		
		public T_Script()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(38,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_questionnaireID", DbType="Decimal(38,0) NOT NULL")]
		public decimal questionnaireID
		{
			get
			{
				return this._questionnaireID;
			}
			set
			{
				if ((this._questionnaireID != value))
				{
					this.OnquestionnaireIDChanging(value);
					this.SendPropertyChanging();
					this._questionnaireID = value;
					this.SendPropertyChanged("questionnaireID");
					this.OnquestionnaireIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_script", DbType="VarChar(50)")]
		public string script
		{
			get
			{
				return this._script;
			}
			set
			{
				if ((this._script != value))
				{
					this.OnscriptChanging(value);
					this.SendPropertyChanging();
					this._script = value;
					this.SendPropertyChanged("script");
					this.OnscriptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contents", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary contents
		{
			get
			{
				return this._contents;
			}
			set
			{
				if ((this._contents != value))
				{
					this.OncontentsChanging(value);
					this.SendPropertyChanging();
					this._contents = value;
					this.SendPropertyChanged("contents");
					this.OncontentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hashString", DbType="VarChar(32)")]
		public string hashString
		{
			get
			{
				return this._hashString;
			}
			set
			{
				if ((this._hashString != value))
				{
					this.OnhashStringChanging(value);
					this.SendPropertyChanging();
					this._hashString = value;
					this.SendPropertyChanged("hashString");
					this.OnhashStringChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDateTime", DbType="DateTime NOT NULL")]
		public System.DateTime createDateTime
		{
			get
			{
				return this._createDateTime;
			}
			set
			{
				if ((this._createDateTime != value))
				{
					this.OncreateDateTimeChanging(value);
					this.SendPropertyChanging();
					this._createDateTime = value;
					this.SendPropertyChanged("createDateTime");
					this.OncreateDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_variableList", DbType="Xml", UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement variableList
		{
			get
			{
				return this._variableList;
			}
			set
			{
				if ((this._variableList != value))
				{
					this.OnvariableListChanging(value);
					this.SendPropertyChanging();
					this._variableList = value;
					this.SendPropertyChanged("variableList");
					this.OnvariableListChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quotaVariableList", DbType="Xml", UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement quotaVariableList
		{
			get
			{
				return this._quotaVariableList;
			}
			set
			{
				if ((this._quotaVariableList != value))
				{
					this.OnquotaVariableListChanging(value);
					this.SendPropertyChanging();
					this._quotaVariableList = value;
					this.SendPropertyChanged("quotaVariableList");
					this.OnquotaVariableListChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quotaList", DbType="Xml", UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement quotaList
		{
			get
			{
				return this._quotaList;
			}
			set
			{
				if ((this._quotaList != value))
				{
					this.OnquotaListChanging(value);
					this.SendPropertyChanging();
					this._quotaList = value;
					this.SendPropertyChanged("quotaList");
					this.OnquotaListChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rotationInfo", DbType="Xml", UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement rotationInfo
		{
			get
			{
				return this._rotationInfo;
			}
			set
			{
				if ((this._rotationInfo != value))
				{
					this.OnrotationInfoChanging(value);
					this.SendPropertyChanging();
					this._rotationInfo = value;
					this.SendPropertyChanged("rotationInfo");
					this.OnrotationInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parser", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary parser
		{
			get
			{
				return this._parser;
			}
			set
			{
				if ((this._parser != value))
				{
					this.OnparserChanging(value);
					this.SendPropertyChanging();
					this._parser = value;
					this.SendPropertyChanged("parser");
					this.OnparserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_InterviewerLoginInfo")]
	public partial class T_InterviewerLoginInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id;
		
		private decimal _employeeNumber;
		
		private System.DateTime _loginDateTime;
		
    #region 확장성 메서드 정의
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(decimal value);
    partial void OnidChanged();
    partial void OnemployeeNumberChanging(decimal value);
    partial void OnemployeeNumberChanged();
    partial void OnloginDateTimeChanging(System.DateTime value);
    partial void OnloginDateTimeChanged();
    #endregion
		
		public T_InterviewerLoginInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(38,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employeeNumber", DbType="Decimal(38,0) NOT NULL")]
		public decimal employeeNumber
		{
			get
			{
				return this._employeeNumber;
			}
			set
			{
				if ((this._employeeNumber != value))
				{
					this.OnemployeeNumberChanging(value);
					this.SendPropertyChanging();
					this._employeeNumber = value;
					this.SendPropertyChanged("employeeNumber");
					this.OnemployeeNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loginDateTime", DbType="DateTime NOT NULL")]
		public System.DateTime loginDateTime
		{
			get
			{
				return this._loginDateTime;
			}
			set
			{
				if ((this._loginDateTime != value))
				{
					this.OnloginDateTimeChanging(value);
					this.SendPropertyChanging();
					this._loginDateTime = value;
					this.SendPropertyChanged("loginDateTime");
					this.OnloginDateTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Questionnaire")]
	public partial class T_Questionnaire : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id;
		
		private string _pof;
		
		private string _questionnaireNumber;
		
		private string _questionnaireName;
		
		private string _questionnairePersonName;
		
		private string _questionnaireType;
		
		private string _surveySequenceNumber;
		
		private string _researcherName;
		
		private string _fieldWorkerName;
		
		private System.Nullable<decimal> _assignCount;
		
		private short _fieldWorkYN;
		
		private short _deleteYN;
		
		private System.DateTime _createDateTime;
		
		private System.DateTime _updateDateTime;
		
		private System.Nullable<short> _editYN;
		
		private System.Nullable<short> _viewCodeYN;
		
    #region 확장성 메서드 정의
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(decimal value);
    partial void OnidChanged();
    partial void OnpofChanging(string value);
    partial void OnpofChanged();
    partial void OnquestionnaireNumberChanging(string value);
    partial void OnquestionnaireNumberChanged();
    partial void OnquestionnaireNameChanging(string value);
    partial void OnquestionnaireNameChanged();
    partial void OnquestionnairePersonNameChanging(string value);
    partial void OnquestionnairePersonNameChanged();
    partial void OnquestionnaireTypeChanging(string value);
    partial void OnquestionnaireTypeChanged();
    partial void OnsurveySequenceNumberChanging(string value);
    partial void OnsurveySequenceNumberChanged();
    partial void OnresearcherNameChanging(string value);
    partial void OnresearcherNameChanged();
    partial void OnfieldWorkerNameChanging(string value);
    partial void OnfieldWorkerNameChanged();
    partial void OnassignCountChanging(System.Nullable<decimal> value);
    partial void OnassignCountChanged();
    partial void OnfieldWorkYNChanging(short value);
    partial void OnfieldWorkYNChanged();
    partial void OndeleteYNChanging(short value);
    partial void OndeleteYNChanged();
    partial void OncreateDateTimeChanging(System.DateTime value);
    partial void OncreateDateTimeChanged();
    partial void OnupdateDateTimeChanging(System.DateTime value);
    partial void OnupdateDateTimeChanged();
    partial void OneditYNChanging(System.Nullable<short> value);
    partial void OneditYNChanged();
    partial void OnviewCodeYNChanging(System.Nullable<short> value);
    partial void OnviewCodeYNChanged();
    #endregion
		
		public T_Questionnaire()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(38,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pof", DbType="VarChar(20)")]
		public string pof
		{
			get
			{
				return this._pof;
			}
			set
			{
				if ((this._pof != value))
				{
					this.OnpofChanging(value);
					this.SendPropertyChanging();
					this._pof = value;
					this.SendPropertyChanged("pof");
					this.OnpofChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_questionnaireNumber", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string questionnaireNumber
		{
			get
			{
				return this._questionnaireNumber;
			}
			set
			{
				if ((this._questionnaireNumber != value))
				{
					this.OnquestionnaireNumberChanging(value);
					this.SendPropertyChanging();
					this._questionnaireNumber = value;
					this.SendPropertyChanged("questionnaireNumber");
					this.OnquestionnaireNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_questionnaireName", DbType="VarChar(200)")]
		public string questionnaireName
		{
			get
			{
				return this._questionnaireName;
			}
			set
			{
				if ((this._questionnaireName != value))
				{
					this.OnquestionnaireNameChanging(value);
					this.SendPropertyChanging();
					this._questionnaireName = value;
					this.SendPropertyChanged("questionnaireName");
					this.OnquestionnaireNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_questionnairePersonName", DbType="VarChar(50)")]
		public string questionnairePersonName
		{
			get
			{
				return this._questionnairePersonName;
			}
			set
			{
				if ((this._questionnairePersonName != value))
				{
					this.OnquestionnairePersonNameChanging(value);
					this.SendPropertyChanging();
					this._questionnairePersonName = value;
					this.SendPropertyChanged("questionnairePersonName");
					this.OnquestionnairePersonNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_questionnaireType", DbType="VarChar(50)")]
		public string questionnaireType
		{
			get
			{
				return this._questionnaireType;
			}
			set
			{
				if ((this._questionnaireType != value))
				{
					this.OnquestionnaireTypeChanging(value);
					this.SendPropertyChanging();
					this._questionnaireType = value;
					this.SendPropertyChanged("questionnaireType");
					this.OnquestionnaireTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_surveySequenceNumber", DbType="VarChar(10)")]
		public string surveySequenceNumber
		{
			get
			{
				return this._surveySequenceNumber;
			}
			set
			{
				if ((this._surveySequenceNumber != value))
				{
					this.OnsurveySequenceNumberChanging(value);
					this.SendPropertyChanging();
					this._surveySequenceNumber = value;
					this.SendPropertyChanged("surveySequenceNumber");
					this.OnsurveySequenceNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_researcherName", DbType="VarChar(50)")]
		public string researcherName
		{
			get
			{
				return this._researcherName;
			}
			set
			{
				if ((this._researcherName != value))
				{
					this.OnresearcherNameChanging(value);
					this.SendPropertyChanging();
					this._researcherName = value;
					this.SendPropertyChanged("researcherName");
					this.OnresearcherNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fieldWorkerName", DbType="VarChar(50)")]
		public string fieldWorkerName
		{
			get
			{
				return this._fieldWorkerName;
			}
			set
			{
				if ((this._fieldWorkerName != value))
				{
					this.OnfieldWorkerNameChanging(value);
					this.SendPropertyChanging();
					this._fieldWorkerName = value;
					this.SendPropertyChanged("fieldWorkerName");
					this.OnfieldWorkerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_assignCount", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> assignCount
		{
			get
			{
				return this._assignCount;
			}
			set
			{
				if ((this._assignCount != value))
				{
					this.OnassignCountChanging(value);
					this.SendPropertyChanging();
					this._assignCount = value;
					this.SendPropertyChanged("assignCount");
					this.OnassignCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fieldWorkYN", DbType="SmallInt NOT NULL")]
		public short fieldWorkYN
		{
			get
			{
				return this._fieldWorkYN;
			}
			set
			{
				if ((this._fieldWorkYN != value))
				{
					this.OnfieldWorkYNChanging(value);
					this.SendPropertyChanging();
					this._fieldWorkYN = value;
					this.SendPropertyChanged("fieldWorkYN");
					this.OnfieldWorkYNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleteYN", DbType="SmallInt NOT NULL")]
		public short deleteYN
		{
			get
			{
				return this._deleteYN;
			}
			set
			{
				if ((this._deleteYN != value))
				{
					this.OndeleteYNChanging(value);
					this.SendPropertyChanging();
					this._deleteYN = value;
					this.SendPropertyChanged("deleteYN");
					this.OndeleteYNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDateTime", DbType="DateTime NOT NULL")]
		public System.DateTime createDateTime
		{
			get
			{
				return this._createDateTime;
			}
			set
			{
				if ((this._createDateTime != value))
				{
					this.OncreateDateTimeChanging(value);
					this.SendPropertyChanging();
					this._createDateTime = value;
					this.SendPropertyChanged("createDateTime");
					this.OncreateDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updateDateTime", DbType="DateTime NOT NULL")]
		public System.DateTime updateDateTime
		{
			get
			{
				return this._updateDateTime;
			}
			set
			{
				if ((this._updateDateTime != value))
				{
					this.OnupdateDateTimeChanging(value);
					this.SendPropertyChanging();
					this._updateDateTime = value;
					this.SendPropertyChanged("updateDateTime");
					this.OnupdateDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_editYN", DbType="SmallInt")]
		public System.Nullable<short> editYN
		{
			get
			{
				return this._editYN;
			}
			set
			{
				if ((this._editYN != value))
				{
					this.OneditYNChanging(value);
					this.SendPropertyChanging();
					this._editYN = value;
					this.SendPropertyChanged("editYN");
					this.OneditYNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_viewCodeYN", DbType="SmallInt")]
		public System.Nullable<short> viewCodeYN
		{
			get
			{
				return this._viewCodeYN;
			}
			set
			{
				if ((this._viewCodeYN != value))
				{
					this.OnviewCodeYNChanging(value);
					this.SendPropertyChanging();
					this._viewCodeYN = value;
					this.SendPropertyChanged("viewCodeYN");
					this.OnviewCodeYNChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_EmployeeInfo")]
	public partial class T_EmployeeInfo
	{
		
		private string _사원번호;
		
		private string _부서;
		
		private string _이름;
		
		public T_EmployeeInfo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_사원번호", DbType="NVarChar(50)")]
		public string 사원번호
		{
			get
			{
				return this._사원번호;
			}
			set
			{
				if ((this._사원번호 != value))
				{
					this._사원번호 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_부서", DbType="NVarChar(50)")]
		public string 부서
		{
			get
			{
				return this._부서;
			}
			set
			{
				if ((this._부서 != value))
				{
					this._부서 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_이름", DbType="NVarChar(50)")]
		public string 이름
		{
			get
			{
				return this._이름;
			}
			set
			{
				if ((this._이름 != value))
				{
					this._이름 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_QuestionnaireDistribution")]
	public partial class T_QuestionnaireDistribution : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id;
		
		private System.Nullable<decimal> _employeeNumber;
		
		private System.Nullable<decimal> _questionnaireID;
		
		private System.Nullable<short> _deleteYN;
		
		private System.Nullable<System.DateTime> _createDateTime;
		
		private System.Nullable<System.DateTime> _updateDateTime;
		
		private System.Nullable<System.DateTime> _sendDateTime;
		
		private string _deviceName;
		
		private string _office;
		
		private System.Nullable<int> _office_code;
		
		private string _sv_name;
		
		private string _area;
		
		private System.Nullable<short> _testYN;
		
		private string _etc1;
		
		private string _etc2;
		
		private string _etc3;
		
		private string _etc4;
		
		private string _etc5;
		
		private string _etc6;
		
		private string _etc7;
		
		private string _etc8;
		
		private string _etc9;
		
		private string _etc10;
		
		private string _etc11;
		
		private string _etc12;
		
		private string _etc13;
		
		private string _etc14;
		
		private string _etc15;
		
		private string _etc16;
		
		private string _etc17;
		
		private string _etc18;
		
		private string _etc19;
		
		private string _etc20;
		
    #region 확장성 메서드 정의
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(decimal value);
    partial void OnidChanged();
    partial void OnemployeeNumberChanging(System.Nullable<decimal> value);
    partial void OnemployeeNumberChanged();
    partial void OnquestionnaireIDChanging(System.Nullable<decimal> value);
    partial void OnquestionnaireIDChanged();
    partial void OndeleteYNChanging(System.Nullable<short> value);
    partial void OndeleteYNChanged();
    partial void OncreateDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OncreateDateTimeChanged();
    partial void OnupdateDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnupdateDateTimeChanged();
    partial void OnsendDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnsendDateTimeChanged();
    partial void OndeviceNameChanging(string value);
    partial void OndeviceNameChanged();
    partial void OnofficeChanging(string value);
    partial void OnofficeChanged();
    partial void Onoffice_codeChanging(System.Nullable<int> value);
    partial void Onoffice_codeChanged();
    partial void Onsv_nameChanging(string value);
    partial void Onsv_nameChanged();
    partial void OnareaChanging(string value);
    partial void OnareaChanged();
    partial void OntestYNChanging(System.Nullable<short> value);
    partial void OntestYNChanged();
    partial void Onetc1Changing(string value);
    partial void Onetc1Changed();
    partial void Onetc2Changing(string value);
    partial void Onetc2Changed();
    partial void Onetc3Changing(string value);
    partial void Onetc3Changed();
    partial void Onetc4Changing(string value);
    partial void Onetc4Changed();
    partial void Onetc5Changing(string value);
    partial void Onetc5Changed();
    partial void Onetc6Changing(string value);
    partial void Onetc6Changed();
    partial void Onetc7Changing(string value);
    partial void Onetc7Changed();
    partial void Onetc8Changing(string value);
    partial void Onetc8Changed();
    partial void Onetc9Changing(string value);
    partial void Onetc9Changed();
    partial void Onetc10Changing(string value);
    partial void Onetc10Changed();
    partial void Onetc11Changing(string value);
    partial void Onetc11Changed();
    partial void Onetc12Changing(string value);
    partial void Onetc12Changed();
    partial void Onetc13Changing(string value);
    partial void Onetc13Changed();
    partial void Onetc14Changing(string value);
    partial void Onetc14Changed();
    partial void Onetc15Changing(string value);
    partial void Onetc15Changed();
    partial void Onetc16Changing(string value);
    partial void Onetc16Changed();
    partial void Onetc17Changing(string value);
    partial void Onetc17Changed();
    partial void Onetc18Changing(string value);
    partial void Onetc18Changed();
    partial void Onetc19Changing(string value);
    partial void Onetc19Changed();
    partial void Onetc20Changing(string value);
    partial void Onetc20Changed();
    #endregion
		
		public T_QuestionnaireDistribution()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(38,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employeeNumber", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> employeeNumber
		{
			get
			{
				return this._employeeNumber;
			}
			set
			{
				if ((this._employeeNumber != value))
				{
					this.OnemployeeNumberChanging(value);
					this.SendPropertyChanging();
					this._employeeNumber = value;
					this.SendPropertyChanged("employeeNumber");
					this.OnemployeeNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_questionnaireID", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> questionnaireID
		{
			get
			{
				return this._questionnaireID;
			}
			set
			{
				if ((this._questionnaireID != value))
				{
					this.OnquestionnaireIDChanging(value);
					this.SendPropertyChanging();
					this._questionnaireID = value;
					this.SendPropertyChanged("questionnaireID");
					this.OnquestionnaireIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleteYN", DbType="SmallInt")]
		public System.Nullable<short> deleteYN
		{
			get
			{
				return this._deleteYN;
			}
			set
			{
				if ((this._deleteYN != value))
				{
					this.OndeleteYNChanging(value);
					this.SendPropertyChanging();
					this._deleteYN = value;
					this.SendPropertyChanged("deleteYN");
					this.OndeleteYNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> createDateTime
		{
			get
			{
				return this._createDateTime;
			}
			set
			{
				if ((this._createDateTime != value))
				{
					this.OncreateDateTimeChanging(value);
					this.SendPropertyChanging();
					this._createDateTime = value;
					this.SendPropertyChanged("createDateTime");
					this.OncreateDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updateDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> updateDateTime
		{
			get
			{
				return this._updateDateTime;
			}
			set
			{
				if ((this._updateDateTime != value))
				{
					this.OnupdateDateTimeChanging(value);
					this.SendPropertyChanging();
					this._updateDateTime = value;
					this.SendPropertyChanged("updateDateTime");
					this.OnupdateDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sendDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> sendDateTime
		{
			get
			{
				return this._sendDateTime;
			}
			set
			{
				if ((this._sendDateTime != value))
				{
					this.OnsendDateTimeChanging(value);
					this.SendPropertyChanging();
					this._sendDateTime = value;
					this.SendPropertyChanged("sendDateTime");
					this.OnsendDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deviceName", DbType="NVarChar(50)")]
		public string deviceName
		{
			get
			{
				return this._deviceName;
			}
			set
			{
				if ((this._deviceName != value))
				{
					this.OndeviceNameChanging(value);
					this.SendPropertyChanging();
					this._deviceName = value;
					this.SendPropertyChanged("deviceName");
					this.OndeviceNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_office", DbType="NVarChar(50)")]
		public string office
		{
			get
			{
				return this._office;
			}
			set
			{
				if ((this._office != value))
				{
					this.OnofficeChanging(value);
					this.SendPropertyChanging();
					this._office = value;
					this.SendPropertyChanged("office");
					this.OnofficeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_office_code", DbType="Int")]
		public System.Nullable<int> office_code
		{
			get
			{
				return this._office_code;
			}
			set
			{
				if ((this._office_code != value))
				{
					this.Onoffice_codeChanging(value);
					this.SendPropertyChanging();
					this._office_code = value;
					this.SendPropertyChanged("office_code");
					this.Onoffice_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sv_name", DbType="NVarChar(50)")]
		public string sv_name
		{
			get
			{
				return this._sv_name;
			}
			set
			{
				if ((this._sv_name != value))
				{
					this.Onsv_nameChanging(value);
					this.SendPropertyChanging();
					this._sv_name = value;
					this.SendPropertyChanged("sv_name");
					this.Onsv_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_area", DbType="NVarChar(50)")]
		public string area
		{
			get
			{
				return this._area;
			}
			set
			{
				if ((this._area != value))
				{
					this.OnareaChanging(value);
					this.SendPropertyChanging();
					this._area = value;
					this.SendPropertyChanged("area");
					this.OnareaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_testYN", DbType="SmallInt")]
		public System.Nullable<short> testYN
		{
			get
			{
				return this._testYN;
			}
			set
			{
				if ((this._testYN != value))
				{
					this.OntestYNChanging(value);
					this.SendPropertyChanging();
					this._testYN = value;
					this.SendPropertyChanged("testYN");
					this.OntestYNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etc1", DbType="NVarChar(255)")]
		public string etc1
		{
			get
			{
				return this._etc1;
			}
			set
			{
				if ((this._etc1 != value))
				{
					this.Onetc1Changing(value);
					this.SendPropertyChanging();
					this._etc1 = value;
					this.SendPropertyChanged("etc1");
					this.Onetc1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etc2", DbType="NVarChar(255)")]
		public string etc2
		{
			get
			{
				return this._etc2;
			}
			set
			{
				if ((this._etc2 != value))
				{
					this.Onetc2Changing(value);
					this.SendPropertyChanging();
					this._etc2 = value;
					this.SendPropertyChanged("etc2");
					this.Onetc2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etc3", DbType="NVarChar(255)")]
		public string etc3
		{
			get
			{
				return this._etc3;
			}
			set
			{
				if ((this._etc3 != value))
				{
					this.Onetc3Changing(value);
					this.SendPropertyChanging();
					this._etc3 = value;
					this.SendPropertyChanged("etc3");
					this.Onetc3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etc4", DbType="NVarChar(255)")]
		public string etc4
		{
			get
			{
				return this._etc4;
			}
			set
			{
				if ((this._etc4 != value))
				{
					this.Onetc4Changing(value);
					this.SendPropertyChanging();
					this._etc4 = value;
					this.SendPropertyChanged("etc4");
					this.Onetc4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etc5", DbType="NVarChar(255)")]
		public string etc5
		{
			get
			{
				return this._etc5;
			}
			set
			{
				if ((this._etc5 != value))
				{
					this.Onetc5Changing(value);
					this.SendPropertyChanging();
					this._etc5 = value;
					this.SendPropertyChanged("etc5");
					this.Onetc5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etc6", DbType="NVarChar(255)")]
		public string etc6
		{
			get
			{
				return this._etc6;
			}
			set
			{
				if ((this._etc6 != value))
				{
					this.Onetc6Changing(value);
					this.SendPropertyChanging();
					this._etc6 = value;
					this.SendPropertyChanged("etc6");
					this.Onetc6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etc7", DbType="NVarChar(255)")]
		public string etc7
		{
			get
			{
				return this._etc7;
			}
			set
			{
				if ((this._etc7 != value))
				{
					this.Onetc7Changing(value);
					this.SendPropertyChanging();
					this._etc7 = value;
					this.SendPropertyChanged("etc7");
					this.Onetc7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etc8", DbType="NVarChar(255)")]
		public string etc8
		{
			get
			{
				return this._etc8;
			}
			set
			{
				if ((this._etc8 != value))
				{
					this.Onetc8Changing(value);
					this.SendPropertyChanging();
					this._etc8 = value;
					this.SendPropertyChanged("etc8");
					this.Onetc8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etc9", DbType="NVarChar(255)")]
		public string etc9
		{
			get
			{
				return this._etc9;
			}
			set
			{
				if ((this._etc9 != value))
				{
					this.Onetc9Changing(value);
					this.SendPropertyChanging();
					this._etc9 = value;
					this.SendPropertyChanged("etc9");
					this.Onetc9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etc10", DbType="NVarChar(255)")]
		public string etc10
		{
			get
			{
				return this._etc10;
			}
			set
			{
				if ((this._etc10 != value))
				{
					this.Onetc10Changing(value);
					this.SendPropertyChanging();
					this._etc10 = value;
					this.SendPropertyChanged("etc10");
					this.Onetc10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etc11", DbType="NVarChar(255)")]
		public string etc11
		{
			get
			{
				return this._etc11;
			}
			set
			{
				if ((this._etc11 != value))
				{
					this.Onetc11Changing(value);
					this.SendPropertyChanging();
					this._etc11 = value;
					this.SendPropertyChanged("etc11");
					this.Onetc11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etc12", DbType="NVarChar(255)")]
		public string etc12
		{
			get
			{
				return this._etc12;
			}
			set
			{
				if ((this._etc12 != value))
				{
					this.Onetc12Changing(value);
					this.SendPropertyChanging();
					this._etc12 = value;
					this.SendPropertyChanged("etc12");
					this.Onetc12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etc13", DbType="NVarChar(255)")]
		public string etc13
		{
			get
			{
				return this._etc13;
			}
			set
			{
				if ((this._etc13 != value))
				{
					this.Onetc13Changing(value);
					this.SendPropertyChanging();
					this._etc13 = value;
					this.SendPropertyChanged("etc13");
					this.Onetc13Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etc14", DbType="NVarChar(255)")]
		public string etc14
		{
			get
			{
				return this._etc14;
			}
			set
			{
				if ((this._etc14 != value))
				{
					this.Onetc14Changing(value);
					this.SendPropertyChanging();
					this._etc14 = value;
					this.SendPropertyChanged("etc14");
					this.Onetc14Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etc15", DbType="NVarChar(255)")]
		public string etc15
		{
			get
			{
				return this._etc15;
			}
			set
			{
				if ((this._etc15 != value))
				{
					this.Onetc15Changing(value);
					this.SendPropertyChanging();
					this._etc15 = value;
					this.SendPropertyChanged("etc15");
					this.Onetc15Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etc16", DbType="NVarChar(255)")]
		public string etc16
		{
			get
			{
				return this._etc16;
			}
			set
			{
				if ((this._etc16 != value))
				{
					this.Onetc16Changing(value);
					this.SendPropertyChanging();
					this._etc16 = value;
					this.SendPropertyChanged("etc16");
					this.Onetc16Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etc17", DbType="NVarChar(255)")]
		public string etc17
		{
			get
			{
				return this._etc17;
			}
			set
			{
				if ((this._etc17 != value))
				{
					this.Onetc17Changing(value);
					this.SendPropertyChanging();
					this._etc17 = value;
					this.SendPropertyChanged("etc17");
					this.Onetc17Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etc18", DbType="NVarChar(255)")]
		public string etc18
		{
			get
			{
				return this._etc18;
			}
			set
			{
				if ((this._etc18 != value))
				{
					this.Onetc18Changing(value);
					this.SendPropertyChanging();
					this._etc18 = value;
					this.SendPropertyChanged("etc18");
					this.Onetc18Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etc19", DbType="NVarChar(255)")]
		public string etc19
		{
			get
			{
				return this._etc19;
			}
			set
			{
				if ((this._etc19 != value))
				{
					this.Onetc19Changing(value);
					this.SendPropertyChanging();
					this._etc19 = value;
					this.SendPropertyChanged("etc19");
					this.Onetc19Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etc20", DbType="NVarChar(255)")]
		public string etc20
		{
			get
			{
				return this._etc20;
			}
			set
			{
				if ((this._etc20 != value))
				{
					this.Onetc20Changing(value);
					this.SendPropertyChanging();
					this._etc20 = value;
					this.SendPropertyChanged("etc20");
					this.Onetc20Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Quota")]
	public partial class T_Quota : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id;
		
		private System.Nullable<decimal> _questionnaireID;
		
		private string _quotaVariable;
		
		private string _questionVariable;
		
		private System.Nullable<short> _quotaNumber;
		
		private string _exampleValue;
		
		private string _exampleLabel;
		
		private string _quota01;
		
		private string _quota02;
		
		private string _quota03;
		
		private string _quota04;
		
		private string _quota05;
		
		private string _gridPosition;
		
		private System.Nullable<decimal> _assignCount;
		
		private System.Nullable<int> _isEarlyOver;
		
		private System.Nullable<decimal> _completeCount;
		
		private System.Nullable<long> _cawiSuccessCount;
		
		private System.Nullable<long> _capiSuccessCount;
		
		private System.Nullable<long> _catiSuccessCount;
		
		private System.Nullable<long> _piSuccessCount;
		
		private System.Nullable<long> _tapiSuccessCount;
		
		private System.Nullable<long> _cawiQuotaFullCount;
		
		private System.Nullable<long> _capiQuotaFullCount;
		
		private System.Nullable<long> _catiQuotaFullCount;
		
		private System.Nullable<long> _piQuotaFullCount;
		
		private System.Nullable<long> _tapiQuotaFullCount;
		
		private System.Nullable<long> _cawiScreenOutCount;
		
		private System.Nullable<long> _capiScreenOutCount;
		
		private System.Nullable<long> _catiScreenOutCount;
		
		private System.Nullable<long> _piScreenOutCount;
		
		private System.Nullable<long> _tapiScreenOutCount;
		
		private System.Nullable<long> _cawiAnswerStopCount;
		
		private System.Nullable<long> _capiAnswerStopCount;
		
		private System.Nullable<long> _catiAnswerStopCount;
		
		private System.Nullable<long> _piAnswerStopCount;
		
		private System.Nullable<long> _tapiAnswerStopCount;
		
		private System.Nullable<long> _reservationCount;
		
		private System.Nullable<decimal> _ranking;
		
		private System.DateTime _createDateTime;
		
		private System.DateTime _updateDateTime;
		
    #region 확장성 메서드 정의
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(decimal value);
    partial void OnidChanged();
    partial void OnquestionnaireIDChanging(System.Nullable<decimal> value);
    partial void OnquestionnaireIDChanged();
    partial void OnquotaVariableChanging(string value);
    partial void OnquotaVariableChanged();
    partial void OnquestionVariableChanging(string value);
    partial void OnquestionVariableChanged();
    partial void OnquotaNumberChanging(System.Nullable<short> value);
    partial void OnquotaNumberChanged();
    partial void OnexampleValueChanging(string value);
    partial void OnexampleValueChanged();
    partial void OnexampleLabelChanging(string value);
    partial void OnexampleLabelChanged();
    partial void Onquota01Changing(string value);
    partial void Onquota01Changed();
    partial void Onquota02Changing(string value);
    partial void Onquota02Changed();
    partial void Onquota03Changing(string value);
    partial void Onquota03Changed();
    partial void Onquota04Changing(string value);
    partial void Onquota04Changed();
    partial void Onquota05Changing(string value);
    partial void Onquota05Changed();
    partial void OngridPositionChanging(string value);
    partial void OngridPositionChanged();
    partial void OnassignCountChanging(System.Nullable<decimal> value);
    partial void OnassignCountChanged();
    partial void OnisEarlyOverChanging(System.Nullable<int> value);
    partial void OnisEarlyOverChanged();
    partial void OncompleteCountChanging(System.Nullable<decimal> value);
    partial void OncompleteCountChanged();
    partial void OncawiSuccessCountChanging(System.Nullable<long> value);
    partial void OncawiSuccessCountChanged();
    partial void OncapiSuccessCountChanging(System.Nullable<long> value);
    partial void OncapiSuccessCountChanged();
    partial void OncatiSuccessCountChanging(System.Nullable<long> value);
    partial void OncatiSuccessCountChanged();
    partial void OnpiSuccessCountChanging(System.Nullable<long> value);
    partial void OnpiSuccessCountChanged();
    partial void OntapiSuccessCountChanging(System.Nullable<long> value);
    partial void OntapiSuccessCountChanged();
    partial void OncawiQuotaFullCountChanging(System.Nullable<long> value);
    partial void OncawiQuotaFullCountChanged();
    partial void OncapiQuotaFullCountChanging(System.Nullable<long> value);
    partial void OncapiQuotaFullCountChanged();
    partial void OncatiQuotaFullCountChanging(System.Nullable<long> value);
    partial void OncatiQuotaFullCountChanged();
    partial void OnpiQuotaFullCountChanging(System.Nullable<long> value);
    partial void OnpiQuotaFullCountChanged();
    partial void OntapiQuotaFullCountChanging(System.Nullable<long> value);
    partial void OntapiQuotaFullCountChanged();
    partial void OncawiScreenOutCountChanging(System.Nullable<long> value);
    partial void OncawiScreenOutCountChanged();
    partial void OncapiScreenOutCountChanging(System.Nullable<long> value);
    partial void OncapiScreenOutCountChanged();
    partial void OncatiScreenOutCountChanging(System.Nullable<long> value);
    partial void OncatiScreenOutCountChanged();
    partial void OnpiScreenOutCountChanging(System.Nullable<long> value);
    partial void OnpiScreenOutCountChanged();
    partial void OntapiScreenOutCountChanging(System.Nullable<long> value);
    partial void OntapiScreenOutCountChanged();
    partial void OncawiAnswerStopCountChanging(System.Nullable<long> value);
    partial void OncawiAnswerStopCountChanged();
    partial void OncapiAnswerStopCountChanging(System.Nullable<long> value);
    partial void OncapiAnswerStopCountChanged();
    partial void OncatiAnswerStopCountChanging(System.Nullable<long> value);
    partial void OncatiAnswerStopCountChanged();
    partial void OnpiAnswerStopCountChanging(System.Nullable<long> value);
    partial void OnpiAnswerStopCountChanged();
    partial void OntapiAnswerStopCountChanging(System.Nullable<long> value);
    partial void OntapiAnswerStopCountChanged();
    partial void OnreservationCountChanging(System.Nullable<long> value);
    partial void OnreservationCountChanged();
    partial void OnrankingChanging(System.Nullable<decimal> value);
    partial void OnrankingChanged();
    partial void OncreateDateTimeChanging(System.DateTime value);
    partial void OncreateDateTimeChanged();
    partial void OnupdateDateTimeChanging(System.DateTime value);
    partial void OnupdateDateTimeChanged();
    #endregion
		
		public T_Quota()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(38,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_questionnaireID", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> questionnaireID
		{
			get
			{
				return this._questionnaireID;
			}
			set
			{
				if ((this._questionnaireID != value))
				{
					this.OnquestionnaireIDChanging(value);
					this.SendPropertyChanging();
					this._questionnaireID = value;
					this.SendPropertyChanged("questionnaireID");
					this.OnquestionnaireIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quotaVariable", DbType="VarChar(100)")]
		public string quotaVariable
		{
			get
			{
				return this._quotaVariable;
			}
			set
			{
				if ((this._quotaVariable != value))
				{
					this.OnquotaVariableChanging(value);
					this.SendPropertyChanging();
					this._quotaVariable = value;
					this.SendPropertyChanged("quotaVariable");
					this.OnquotaVariableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_questionVariable", DbType="VarChar(100)")]
		public string questionVariable
		{
			get
			{
				return this._questionVariable;
			}
			set
			{
				if ((this._questionVariable != value))
				{
					this.OnquestionVariableChanging(value);
					this.SendPropertyChanging();
					this._questionVariable = value;
					this.SendPropertyChanged("questionVariable");
					this.OnquestionVariableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quotaNumber", DbType="SmallInt")]
		public System.Nullable<short> quotaNumber
		{
			get
			{
				return this._quotaNumber;
			}
			set
			{
				if ((this._quotaNumber != value))
				{
					this.OnquotaNumberChanging(value);
					this.SendPropertyChanging();
					this._quotaNumber = value;
					this.SendPropertyChanged("quotaNumber");
					this.OnquotaNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exampleValue", DbType="VarChar(100)")]
		public string exampleValue
		{
			get
			{
				return this._exampleValue;
			}
			set
			{
				if ((this._exampleValue != value))
				{
					this.OnexampleValueChanging(value);
					this.SendPropertyChanging();
					this._exampleValue = value;
					this.SendPropertyChanged("exampleValue");
					this.OnexampleValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exampleLabel", DbType="VarChar(100)")]
		public string exampleLabel
		{
			get
			{
				return this._exampleLabel;
			}
			set
			{
				if ((this._exampleLabel != value))
				{
					this.OnexampleLabelChanging(value);
					this.SendPropertyChanging();
					this._exampleLabel = value;
					this.SendPropertyChanged("exampleLabel");
					this.OnexampleLabelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quota01", DbType="VarChar(10)")]
		public string quota01
		{
			get
			{
				return this._quota01;
			}
			set
			{
				if ((this._quota01 != value))
				{
					this.Onquota01Changing(value);
					this.SendPropertyChanging();
					this._quota01 = value;
					this.SendPropertyChanged("quota01");
					this.Onquota01Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quota02", DbType="VarChar(10)")]
		public string quota02
		{
			get
			{
				return this._quota02;
			}
			set
			{
				if ((this._quota02 != value))
				{
					this.Onquota02Changing(value);
					this.SendPropertyChanging();
					this._quota02 = value;
					this.SendPropertyChanged("quota02");
					this.Onquota02Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quota03", DbType="VarChar(10)")]
		public string quota03
		{
			get
			{
				return this._quota03;
			}
			set
			{
				if ((this._quota03 != value))
				{
					this.Onquota03Changing(value);
					this.SendPropertyChanging();
					this._quota03 = value;
					this.SendPropertyChanged("quota03");
					this.Onquota03Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quota04", DbType="VarChar(10)")]
		public string quota04
		{
			get
			{
				return this._quota04;
			}
			set
			{
				if ((this._quota04 != value))
				{
					this.Onquota04Changing(value);
					this.SendPropertyChanging();
					this._quota04 = value;
					this.SendPropertyChanged("quota04");
					this.Onquota04Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quota05", DbType="VarChar(10)")]
		public string quota05
		{
			get
			{
				return this._quota05;
			}
			set
			{
				if ((this._quota05 != value))
				{
					this.Onquota05Changing(value);
					this.SendPropertyChanging();
					this._quota05 = value;
					this.SendPropertyChanged("quota05");
					this.Onquota05Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gridPosition", DbType="VarChar(100)")]
		public string gridPosition
		{
			get
			{
				return this._gridPosition;
			}
			set
			{
				if ((this._gridPosition != value))
				{
					this.OngridPositionChanging(value);
					this.SendPropertyChanging();
					this._gridPosition = value;
					this.SendPropertyChanged("gridPosition");
					this.OngridPositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_assignCount", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> assignCount
		{
			get
			{
				return this._assignCount;
			}
			set
			{
				if ((this._assignCount != value))
				{
					this.OnassignCountChanging(value);
					this.SendPropertyChanging();
					this._assignCount = value;
					this.SendPropertyChanged("assignCount");
					this.OnassignCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isEarlyOver", DbType="Int")]
		public System.Nullable<int> isEarlyOver
		{
			get
			{
				return this._isEarlyOver;
			}
			set
			{
				if ((this._isEarlyOver != value))
				{
					this.OnisEarlyOverChanging(value);
					this.SendPropertyChanging();
					this._isEarlyOver = value;
					this.SendPropertyChanged("isEarlyOver");
					this.OnisEarlyOverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_completeCount", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> completeCount
		{
			get
			{
				return this._completeCount;
			}
			set
			{
				if ((this._completeCount != value))
				{
					this.OncompleteCountChanging(value);
					this.SendPropertyChanging();
					this._completeCount = value;
					this.SendPropertyChanged("completeCount");
					this.OncompleteCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cawiSuccessCount", DbType="BigInt")]
		public System.Nullable<long> cawiSuccessCount
		{
			get
			{
				return this._cawiSuccessCount;
			}
			set
			{
				if ((this._cawiSuccessCount != value))
				{
					this.OncawiSuccessCountChanging(value);
					this.SendPropertyChanging();
					this._cawiSuccessCount = value;
					this.SendPropertyChanged("cawiSuccessCount");
					this.OncawiSuccessCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_capiSuccessCount", DbType="BigInt")]
		public System.Nullable<long> capiSuccessCount
		{
			get
			{
				return this._capiSuccessCount;
			}
			set
			{
				if ((this._capiSuccessCount != value))
				{
					this.OncapiSuccessCountChanging(value);
					this.SendPropertyChanging();
					this._capiSuccessCount = value;
					this.SendPropertyChanged("capiSuccessCount");
					this.OncapiSuccessCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_catiSuccessCount", DbType="BigInt")]
		public System.Nullable<long> catiSuccessCount
		{
			get
			{
				return this._catiSuccessCount;
			}
			set
			{
				if ((this._catiSuccessCount != value))
				{
					this.OncatiSuccessCountChanging(value);
					this.SendPropertyChanging();
					this._catiSuccessCount = value;
					this.SendPropertyChanged("catiSuccessCount");
					this.OncatiSuccessCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_piSuccessCount", DbType="BigInt")]
		public System.Nullable<long> piSuccessCount
		{
			get
			{
				return this._piSuccessCount;
			}
			set
			{
				if ((this._piSuccessCount != value))
				{
					this.OnpiSuccessCountChanging(value);
					this.SendPropertyChanging();
					this._piSuccessCount = value;
					this.SendPropertyChanged("piSuccessCount");
					this.OnpiSuccessCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tapiSuccessCount", DbType="BigInt")]
		public System.Nullable<long> tapiSuccessCount
		{
			get
			{
				return this._tapiSuccessCount;
			}
			set
			{
				if ((this._tapiSuccessCount != value))
				{
					this.OntapiSuccessCountChanging(value);
					this.SendPropertyChanging();
					this._tapiSuccessCount = value;
					this.SendPropertyChanged("tapiSuccessCount");
					this.OntapiSuccessCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cawiQuotaFullCount", DbType="BigInt")]
		public System.Nullable<long> cawiQuotaFullCount
		{
			get
			{
				return this._cawiQuotaFullCount;
			}
			set
			{
				if ((this._cawiQuotaFullCount != value))
				{
					this.OncawiQuotaFullCountChanging(value);
					this.SendPropertyChanging();
					this._cawiQuotaFullCount = value;
					this.SendPropertyChanged("cawiQuotaFullCount");
					this.OncawiQuotaFullCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_capiQuotaFullCount", DbType="BigInt")]
		public System.Nullable<long> capiQuotaFullCount
		{
			get
			{
				return this._capiQuotaFullCount;
			}
			set
			{
				if ((this._capiQuotaFullCount != value))
				{
					this.OncapiQuotaFullCountChanging(value);
					this.SendPropertyChanging();
					this._capiQuotaFullCount = value;
					this.SendPropertyChanged("capiQuotaFullCount");
					this.OncapiQuotaFullCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_catiQuotaFullCount", DbType="BigInt")]
		public System.Nullable<long> catiQuotaFullCount
		{
			get
			{
				return this._catiQuotaFullCount;
			}
			set
			{
				if ((this._catiQuotaFullCount != value))
				{
					this.OncatiQuotaFullCountChanging(value);
					this.SendPropertyChanging();
					this._catiQuotaFullCount = value;
					this.SendPropertyChanged("catiQuotaFullCount");
					this.OncatiQuotaFullCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_piQuotaFullCount", DbType="BigInt")]
		public System.Nullable<long> piQuotaFullCount
		{
			get
			{
				return this._piQuotaFullCount;
			}
			set
			{
				if ((this._piQuotaFullCount != value))
				{
					this.OnpiQuotaFullCountChanging(value);
					this.SendPropertyChanging();
					this._piQuotaFullCount = value;
					this.SendPropertyChanged("piQuotaFullCount");
					this.OnpiQuotaFullCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tapiQuotaFullCount", DbType="BigInt")]
		public System.Nullable<long> tapiQuotaFullCount
		{
			get
			{
				return this._tapiQuotaFullCount;
			}
			set
			{
				if ((this._tapiQuotaFullCount != value))
				{
					this.OntapiQuotaFullCountChanging(value);
					this.SendPropertyChanging();
					this._tapiQuotaFullCount = value;
					this.SendPropertyChanged("tapiQuotaFullCount");
					this.OntapiQuotaFullCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cawiScreenOutCount", DbType="BigInt")]
		public System.Nullable<long> cawiScreenOutCount
		{
			get
			{
				return this._cawiScreenOutCount;
			}
			set
			{
				if ((this._cawiScreenOutCount != value))
				{
					this.OncawiScreenOutCountChanging(value);
					this.SendPropertyChanging();
					this._cawiScreenOutCount = value;
					this.SendPropertyChanged("cawiScreenOutCount");
					this.OncawiScreenOutCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_capiScreenOutCount", DbType="BigInt")]
		public System.Nullable<long> capiScreenOutCount
		{
			get
			{
				return this._capiScreenOutCount;
			}
			set
			{
				if ((this._capiScreenOutCount != value))
				{
					this.OncapiScreenOutCountChanging(value);
					this.SendPropertyChanging();
					this._capiScreenOutCount = value;
					this.SendPropertyChanged("capiScreenOutCount");
					this.OncapiScreenOutCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_catiScreenOutCount", DbType="BigInt")]
		public System.Nullable<long> catiScreenOutCount
		{
			get
			{
				return this._catiScreenOutCount;
			}
			set
			{
				if ((this._catiScreenOutCount != value))
				{
					this.OncatiScreenOutCountChanging(value);
					this.SendPropertyChanging();
					this._catiScreenOutCount = value;
					this.SendPropertyChanged("catiScreenOutCount");
					this.OncatiScreenOutCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_piScreenOutCount", DbType="BigInt")]
		public System.Nullable<long> piScreenOutCount
		{
			get
			{
				return this._piScreenOutCount;
			}
			set
			{
				if ((this._piScreenOutCount != value))
				{
					this.OnpiScreenOutCountChanging(value);
					this.SendPropertyChanging();
					this._piScreenOutCount = value;
					this.SendPropertyChanged("piScreenOutCount");
					this.OnpiScreenOutCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tapiScreenOutCount", DbType="BigInt")]
		public System.Nullable<long> tapiScreenOutCount
		{
			get
			{
				return this._tapiScreenOutCount;
			}
			set
			{
				if ((this._tapiScreenOutCount != value))
				{
					this.OntapiScreenOutCountChanging(value);
					this.SendPropertyChanging();
					this._tapiScreenOutCount = value;
					this.SendPropertyChanged("tapiScreenOutCount");
					this.OntapiScreenOutCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cawiAnswerStopCount", DbType="BigInt")]
		public System.Nullable<long> cawiAnswerStopCount
		{
			get
			{
				return this._cawiAnswerStopCount;
			}
			set
			{
				if ((this._cawiAnswerStopCount != value))
				{
					this.OncawiAnswerStopCountChanging(value);
					this.SendPropertyChanging();
					this._cawiAnswerStopCount = value;
					this.SendPropertyChanged("cawiAnswerStopCount");
					this.OncawiAnswerStopCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_capiAnswerStopCount", DbType="BigInt")]
		public System.Nullable<long> capiAnswerStopCount
		{
			get
			{
				return this._capiAnswerStopCount;
			}
			set
			{
				if ((this._capiAnswerStopCount != value))
				{
					this.OncapiAnswerStopCountChanging(value);
					this.SendPropertyChanging();
					this._capiAnswerStopCount = value;
					this.SendPropertyChanged("capiAnswerStopCount");
					this.OncapiAnswerStopCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_catiAnswerStopCount", DbType="BigInt")]
		public System.Nullable<long> catiAnswerStopCount
		{
			get
			{
				return this._catiAnswerStopCount;
			}
			set
			{
				if ((this._catiAnswerStopCount != value))
				{
					this.OncatiAnswerStopCountChanging(value);
					this.SendPropertyChanging();
					this._catiAnswerStopCount = value;
					this.SendPropertyChanged("catiAnswerStopCount");
					this.OncatiAnswerStopCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_piAnswerStopCount", DbType="BigInt")]
		public System.Nullable<long> piAnswerStopCount
		{
			get
			{
				return this._piAnswerStopCount;
			}
			set
			{
				if ((this._piAnswerStopCount != value))
				{
					this.OnpiAnswerStopCountChanging(value);
					this.SendPropertyChanging();
					this._piAnswerStopCount = value;
					this.SendPropertyChanged("piAnswerStopCount");
					this.OnpiAnswerStopCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tapiAnswerStopCount", DbType="BigInt")]
		public System.Nullable<long> tapiAnswerStopCount
		{
			get
			{
				return this._tapiAnswerStopCount;
			}
			set
			{
				if ((this._tapiAnswerStopCount != value))
				{
					this.OntapiAnswerStopCountChanging(value);
					this.SendPropertyChanging();
					this._tapiAnswerStopCount = value;
					this.SendPropertyChanged("tapiAnswerStopCount");
					this.OntapiAnswerStopCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reservationCount", DbType="BigInt")]
		public System.Nullable<long> reservationCount
		{
			get
			{
				return this._reservationCount;
			}
			set
			{
				if ((this._reservationCount != value))
				{
					this.OnreservationCountChanging(value);
					this.SendPropertyChanging();
					this._reservationCount = value;
					this.SendPropertyChanged("reservationCount");
					this.OnreservationCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ranking", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> ranking
		{
			get
			{
				return this._ranking;
			}
			set
			{
				if ((this._ranking != value))
				{
					this.OnrankingChanging(value);
					this.SendPropertyChanging();
					this._ranking = value;
					this.SendPropertyChanged("ranking");
					this.OnrankingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDateTime", DbType="DateTime NOT NULL")]
		public System.DateTime createDateTime
		{
			get
			{
				return this._createDateTime;
			}
			set
			{
				if ((this._createDateTime != value))
				{
					this.OncreateDateTimeChanging(value);
					this.SendPropertyChanging();
					this._createDateTime = value;
					this.SendPropertyChanged("createDateTime");
					this.OncreateDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updateDateTime", DbType="DateTime NOT NULL")]
		public System.DateTime updateDateTime
		{
			get
			{
				return this._updateDateTime;
			}
			set
			{
				if ((this._updateDateTime != value))
				{
					this.OnupdateDateTimeChanging(value);
					this.SendPropertyChanging();
					this._updateDateTime = value;
					this.SendPropertyChanged("updateDateTime");
					this.OnupdateDateTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class GET_InterviewerInfoResult
	{
		
		private System.Nullable<decimal> _employeeNumber;
		
		private string _userName;
		
		private string _office;
		
		private string _sv_name;
		
		public GET_InterviewerInfoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employeeNumber", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> employeeNumber
		{
			get
			{
				return this._employeeNumber;
			}
			set
			{
				if ((this._employeeNumber != value))
				{
					this._employeeNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="VarChar(100)")]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this._userName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_office", DbType="NVarChar(50)")]
		public string office
		{
			get
			{
				return this._office;
			}
			set
			{
				if ((this._office != value))
				{
					this._office = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sv_name", DbType="NVarChar(50)")]
		public string sv_name
		{
			get
			{
				return this._sv_name;
			}
			set
			{
				if ((this._sv_name != value))
				{
					this._sv_name = value;
				}
			}
		}
	}
	
	public partial class GET_TAPIProjectResult
	{
		
		private string _questionnaireName;
		
		private string _questionnaireNumber;
		
		private string _url;
		
		public GET_TAPIProjectResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_questionnaireName", DbType="NVarChar(200)")]
		public string questionnaireName
		{
			get
			{
				return this._questionnaireName;
			}
			set
			{
				if ((this._questionnaireName != value))
				{
					this._questionnaireName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_questionnaireNumber", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string questionnaireNumber
		{
			get
			{
				return this._questionnaireNumber;
			}
			set
			{
				if ((this._questionnaireNumber != value))
				{
					this._questionnaireNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_url", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this._url = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
