#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAPI_Interviewer.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WebDiary_Horse2014")]
	public partial class WebDiary_Horse2014DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 확장성 메서드 정의
    partial void OnCreated();
    partial void InsertH_Panel(H_Panel instance);
    partial void UpdateH_Panel(H_Panel instance);
    partial void DeleteH_Panel(H_Panel instance);
    partial void InsertH_NewPanel(H_NewPanel instance);
    partial void UpdateH_NewPanel(H_NewPanel instance);
    partial void DeleteH_NewPanel(H_NewPanel instance);
    #endregion
		
		public WebDiary_Horse2014DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["WebDiary_Horse2014ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public WebDiary_Horse2014DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WebDiary_Horse2014DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WebDiary_Horse2014DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WebDiary_Horse2014DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<H_Panel> H_Panels
		{
			get
			{
				return this.GetTable<H_Panel>();
			}
		}
		
		public System.Data.Linq.Table<H_NewPanel> H_NewPanels
		{
			get
			{
				return this.GetTable<H_NewPanel>();
			}
		}
		
		public System.Data.Linq.Table<H_Member> H_Members
		{
			get
			{
				return this.GetTable<H_Member>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.H_Panel")]
	public partial class H_Panel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idx;
		
		private int _Chasu;
		
		private string _PanelCode;
		
		private string _List_Authorship;
		
		private string _List_Authorship_Code;
		
		private string _Industry_Type;
		
		private string _IsHaveHorseLabel;
		
		private int _IsHaveHorseCode;
		
		private string _BusinessTypeLabel;
		
		private string _BusinessTypeCode;
		
		private string _PanelName;
		
		private string _Owner;
		
		private string _Owner2;
		
		private string _Address;
		
		private string _SidoLabel;
		
		private System.Nullable<int> _SidoCode;
		
		private string _SigunguLabel;
		
		private System.Nullable<int> _SigunguCode;
		
		private string _DongLabel;
		
		private string _RiLabel;
		
		private string _Phone1;
		
		private string _Phone2;
		
		private string _Phone3;
		
		private string _Phone4;
		
		private System.Nullable<int> _IsUpdateCheck;
		
    #region 확장성 메서드 정의
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidxChanging(int value);
    partial void OnidxChanged();
    partial void OnChasuChanging(int value);
    partial void OnChasuChanged();
    partial void OnPanelCodeChanging(string value);
    partial void OnPanelCodeChanged();
    partial void OnList_AuthorshipChanging(string value);
    partial void OnList_AuthorshipChanged();
    partial void OnList_Authorship_CodeChanging(string value);
    partial void OnList_Authorship_CodeChanged();
    partial void OnIndustry_TypeChanging(string value);
    partial void OnIndustry_TypeChanged();
    partial void OnIsHaveHorseLabelChanging(string value);
    partial void OnIsHaveHorseLabelChanged();
    partial void OnIsHaveHorseCodeChanging(int value);
    partial void OnIsHaveHorseCodeChanged();
    partial void OnBusinessTypeLabelChanging(string value);
    partial void OnBusinessTypeLabelChanged();
    partial void OnBusinessTypeCodeChanging(string value);
    partial void OnBusinessTypeCodeChanged();
    partial void OnPanelNameChanging(string value);
    partial void OnPanelNameChanged();
    partial void OnOwnerChanging(string value);
    partial void OnOwnerChanged();
    partial void OnOwner2Changing(string value);
    partial void OnOwner2Changed();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnSidoLabelChanging(string value);
    partial void OnSidoLabelChanged();
    partial void OnSidoCodeChanging(System.Nullable<int> value);
    partial void OnSidoCodeChanged();
    partial void OnSigunguLabelChanging(string value);
    partial void OnSigunguLabelChanged();
    partial void OnSigunguCodeChanging(System.Nullable<int> value);
    partial void OnSigunguCodeChanged();
    partial void OnDongLabelChanging(string value);
    partial void OnDongLabelChanged();
    partial void OnRiLabelChanging(string value);
    partial void OnRiLabelChanged();
    partial void OnPhone1Changing(string value);
    partial void OnPhone1Changed();
    partial void OnPhone2Changing(string value);
    partial void OnPhone2Changed();
    partial void OnPhone3Changing(string value);
    partial void OnPhone3Changed();
    partial void OnPhone4Changing(string value);
    partial void OnPhone4Changed();
    partial void OnIsUpdateCheckChanging(System.Nullable<int> value);
    partial void OnIsUpdateCheckChanged();
    #endregion
		
		public H_Panel()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idx", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idx
		{
			get
			{
				return this._idx;
			}
			set
			{
				if ((this._idx != value))
				{
					this.OnidxChanging(value);
					this.SendPropertyChanging();
					this._idx = value;
					this.SendPropertyChanged("idx");
					this.OnidxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chasu", DbType="Int NOT NULL")]
		public int Chasu
		{
			get
			{
				return this._Chasu;
			}
			set
			{
				if ((this._Chasu != value))
				{
					this.OnChasuChanging(value);
					this.SendPropertyChanging();
					this._Chasu = value;
					this.SendPropertyChanged("Chasu");
					this.OnChasuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PanelCode", DbType="VarChar(50)")]
		public string PanelCode
		{
			get
			{
				return this._PanelCode;
			}
			set
			{
				if ((this._PanelCode != value))
				{
					this.OnPanelCodeChanging(value);
					this.SendPropertyChanging();
					this._PanelCode = value;
					this.SendPropertyChanged("PanelCode");
					this.OnPanelCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_List_Authorship", DbType="VarChar(200)")]
		public string List_Authorship
		{
			get
			{
				return this._List_Authorship;
			}
			set
			{
				if ((this._List_Authorship != value))
				{
					this.OnList_AuthorshipChanging(value);
					this.SendPropertyChanging();
					this._List_Authorship = value;
					this.SendPropertyChanged("List_Authorship");
					this.OnList_AuthorshipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_List_Authorship_Code", DbType="VarChar(50)")]
		public string List_Authorship_Code
		{
			get
			{
				return this._List_Authorship_Code;
			}
			set
			{
				if ((this._List_Authorship_Code != value))
				{
					this.OnList_Authorship_CodeChanging(value);
					this.SendPropertyChanging();
					this._List_Authorship_Code = value;
					this.SendPropertyChanged("List_Authorship_Code");
					this.OnList_Authorship_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Industry_Type", DbType="VarChar(50)")]
		public string Industry_Type
		{
			get
			{
				return this._Industry_Type;
			}
			set
			{
				if ((this._Industry_Type != value))
				{
					this.OnIndustry_TypeChanging(value);
					this.SendPropertyChanging();
					this._Industry_Type = value;
					this.SendPropertyChanged("Industry_Type");
					this.OnIndustry_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHaveHorseLabel", DbType="VarChar(50)")]
		public string IsHaveHorseLabel
		{
			get
			{
				return this._IsHaveHorseLabel;
			}
			set
			{
				if ((this._IsHaveHorseLabel != value))
				{
					this.OnIsHaveHorseLabelChanging(value);
					this.SendPropertyChanging();
					this._IsHaveHorseLabel = value;
					this.SendPropertyChanged("IsHaveHorseLabel");
					this.OnIsHaveHorseLabelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHaveHorseCode", DbType="Int NOT NULL")]
		public int IsHaveHorseCode
		{
			get
			{
				return this._IsHaveHorseCode;
			}
			set
			{
				if ((this._IsHaveHorseCode != value))
				{
					this.OnIsHaveHorseCodeChanging(value);
					this.SendPropertyChanging();
					this._IsHaveHorseCode = value;
					this.SendPropertyChanged("IsHaveHorseCode");
					this.OnIsHaveHorseCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessTypeLabel", DbType="VarChar(50)")]
		public string BusinessTypeLabel
		{
			get
			{
				return this._BusinessTypeLabel;
			}
			set
			{
				if ((this._BusinessTypeLabel != value))
				{
					this.OnBusinessTypeLabelChanging(value);
					this.SendPropertyChanging();
					this._BusinessTypeLabel = value;
					this.SendPropertyChanged("BusinessTypeLabel");
					this.OnBusinessTypeLabelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessTypeCode", DbType="VarChar(50)")]
		public string BusinessTypeCode
		{
			get
			{
				return this._BusinessTypeCode;
			}
			set
			{
				if ((this._BusinessTypeCode != value))
				{
					this.OnBusinessTypeCodeChanging(value);
					this.SendPropertyChanging();
					this._BusinessTypeCode = value;
					this.SendPropertyChanged("BusinessTypeCode");
					this.OnBusinessTypeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PanelName", DbType="VarChar(100)")]
		public string PanelName
		{
			get
			{
				return this._PanelName;
			}
			set
			{
				if ((this._PanelName != value))
				{
					this.OnPanelNameChanging(value);
					this.SendPropertyChanging();
					this._PanelName = value;
					this.SendPropertyChanged("PanelName");
					this.OnPanelNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Owner", DbType="VarChar(100)")]
		public string Owner
		{
			get
			{
				return this._Owner;
			}
			set
			{
				if ((this._Owner != value))
				{
					this.OnOwnerChanging(value);
					this.SendPropertyChanging();
					this._Owner = value;
					this.SendPropertyChanged("Owner");
					this.OnOwnerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Owner2", DbType="VarChar(100)")]
		public string Owner2
		{
			get
			{
				return this._Owner2;
			}
			set
			{
				if ((this._Owner2 != value))
				{
					this.OnOwner2Changing(value);
					this.SendPropertyChanging();
					this._Owner2 = value;
					this.SendPropertyChanged("Owner2");
					this.OnOwner2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(100)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SidoLabel", DbType="VarChar(50)")]
		public string SidoLabel
		{
			get
			{
				return this._SidoLabel;
			}
			set
			{
				if ((this._SidoLabel != value))
				{
					this.OnSidoLabelChanging(value);
					this.SendPropertyChanging();
					this._SidoLabel = value;
					this.SendPropertyChanged("SidoLabel");
					this.OnSidoLabelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SidoCode", DbType="Int")]
		public System.Nullable<int> SidoCode
		{
			get
			{
				return this._SidoCode;
			}
			set
			{
				if ((this._SidoCode != value))
				{
					this.OnSidoCodeChanging(value);
					this.SendPropertyChanging();
					this._SidoCode = value;
					this.SendPropertyChanged("SidoCode");
					this.OnSidoCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SigunguLabel", DbType="VarChar(50)")]
		public string SigunguLabel
		{
			get
			{
				return this._SigunguLabel;
			}
			set
			{
				if ((this._SigunguLabel != value))
				{
					this.OnSigunguLabelChanging(value);
					this.SendPropertyChanging();
					this._SigunguLabel = value;
					this.SendPropertyChanged("SigunguLabel");
					this.OnSigunguLabelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SigunguCode", DbType="Int")]
		public System.Nullable<int> SigunguCode
		{
			get
			{
				return this._SigunguCode;
			}
			set
			{
				if ((this._SigunguCode != value))
				{
					this.OnSigunguCodeChanging(value);
					this.SendPropertyChanging();
					this._SigunguCode = value;
					this.SendPropertyChanged("SigunguCode");
					this.OnSigunguCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DongLabel", DbType="VarChar(50)")]
		public string DongLabel
		{
			get
			{
				return this._DongLabel;
			}
			set
			{
				if ((this._DongLabel != value))
				{
					this.OnDongLabelChanging(value);
					this.SendPropertyChanging();
					this._DongLabel = value;
					this.SendPropertyChanged("DongLabel");
					this.OnDongLabelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RiLabel", DbType="VarChar(50)")]
		public string RiLabel
		{
			get
			{
				return this._RiLabel;
			}
			set
			{
				if ((this._RiLabel != value))
				{
					this.OnRiLabelChanging(value);
					this.SendPropertyChanging();
					this._RiLabel = value;
					this.SendPropertyChanged("RiLabel");
					this.OnRiLabelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone1", DbType="VarChar(50)")]
		public string Phone1
		{
			get
			{
				return this._Phone1;
			}
			set
			{
				if ((this._Phone1 != value))
				{
					this.OnPhone1Changing(value);
					this.SendPropertyChanging();
					this._Phone1 = value;
					this.SendPropertyChanged("Phone1");
					this.OnPhone1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone2", DbType="VarChar(50)")]
		public string Phone2
		{
			get
			{
				return this._Phone2;
			}
			set
			{
				if ((this._Phone2 != value))
				{
					this.OnPhone2Changing(value);
					this.SendPropertyChanging();
					this._Phone2 = value;
					this.SendPropertyChanged("Phone2");
					this.OnPhone2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone3", DbType="VarChar(50)")]
		public string Phone3
		{
			get
			{
				return this._Phone3;
			}
			set
			{
				if ((this._Phone3 != value))
				{
					this.OnPhone3Changing(value);
					this.SendPropertyChanging();
					this._Phone3 = value;
					this.SendPropertyChanged("Phone3");
					this.OnPhone3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone4", DbType="VarChar(50)")]
		public string Phone4
		{
			get
			{
				return this._Phone4;
			}
			set
			{
				if ((this._Phone4 != value))
				{
					this.OnPhone4Changing(value);
					this.SendPropertyChanging();
					this._Phone4 = value;
					this.SendPropertyChanged("Phone4");
					this.OnPhone4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsUpdateCheck", DbType="Int")]
		public System.Nullable<int> IsUpdateCheck
		{
			get
			{
				return this._IsUpdateCheck;
			}
			set
			{
				if ((this._IsUpdateCheck != value))
				{
					this.OnIsUpdateCheckChanging(value);
					this.SendPropertyChanging();
					this._IsUpdateCheck = value;
					this.SendPropertyChanged("IsUpdateCheck");
					this.OnIsUpdateCheckChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.H_NewPanel")]
	public partial class H_NewPanel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idx;
		
		private int _Chasu;
		
		private string _PanelCode;
		
		private string _IsHaveHorseLabel;
		
		private System.Nullable<int> _IsHaveHorseCode;
		
		private string _BusinessTypeLabel;
		
		private string _BusinessTypeLabelEtc;
		
		private string _BusinessTypeCode;
		
		private string _PanelName;
		
		private string _Owner;
		
		private string _Address;
		
		private string _SidoLabel;
		
		private System.Nullable<int> _SidoCode;
		
		private string _SigunguLabel;
		
		private System.Nullable<int> _SigunguCode;
		
		private string _DongLabel;
		
		private string _DetailAddress;
		
		private string _Phone1;
		
		private string _Phone2;
		
		private string _Phone3;
		
		private string _Phone4;
		
		private System.Nullable<int> _IsUpdateCheck;
		
    #region 확장성 메서드 정의
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidxChanging(int value);
    partial void OnidxChanged();
    partial void OnChasuChanging(int value);
    partial void OnChasuChanged();
    partial void OnPanelCodeChanging(string value);
    partial void OnPanelCodeChanged();
    partial void OnIsHaveHorseLabelChanging(string value);
    partial void OnIsHaveHorseLabelChanged();
    partial void OnIsHaveHorseCodeChanging(System.Nullable<int> value);
    partial void OnIsHaveHorseCodeChanged();
    partial void OnBusinessTypeLabelChanging(string value);
    partial void OnBusinessTypeLabelChanged();
    partial void OnBusinessTypeLabelEtcChanging(string value);
    partial void OnBusinessTypeLabelEtcChanged();
    partial void OnBusinessTypeCodeChanging(string value);
    partial void OnBusinessTypeCodeChanged();
    partial void OnPanelNameChanging(string value);
    partial void OnPanelNameChanged();
    partial void OnOwnerChanging(string value);
    partial void OnOwnerChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnSidoLabelChanging(string value);
    partial void OnSidoLabelChanged();
    partial void OnSidoCodeChanging(System.Nullable<int> value);
    partial void OnSidoCodeChanged();
    partial void OnSigunguLabelChanging(string value);
    partial void OnSigunguLabelChanged();
    partial void OnSigunguCodeChanging(System.Nullable<int> value);
    partial void OnSigunguCodeChanged();
    partial void OnDongLabelChanging(string value);
    partial void OnDongLabelChanged();
    partial void OnDetailAddressChanging(string value);
    partial void OnDetailAddressChanged();
    partial void OnPhone1Changing(string value);
    partial void OnPhone1Changed();
    partial void OnPhone2Changing(string value);
    partial void OnPhone2Changed();
    partial void OnPhone3Changing(string value);
    partial void OnPhone3Changed();
    partial void OnPhone4Changing(string value);
    partial void OnPhone4Changed();
    partial void OnIsUpdateCheckChanging(System.Nullable<int> value);
    partial void OnIsUpdateCheckChanged();
    #endregion
		
		public H_NewPanel()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idx", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idx
		{
			get
			{
				return this._idx;
			}
			set
			{
				if ((this._idx != value))
				{
					this.OnidxChanging(value);
					this.SendPropertyChanging();
					this._idx = value;
					this.SendPropertyChanged("idx");
					this.OnidxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chasu", DbType="Int NOT NULL")]
		public int Chasu
		{
			get
			{
				return this._Chasu;
			}
			set
			{
				if ((this._Chasu != value))
				{
					this.OnChasuChanging(value);
					this.SendPropertyChanging();
					this._Chasu = value;
					this.SendPropertyChanged("Chasu");
					this.OnChasuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PanelCode", DbType="VarChar(50)")]
		public string PanelCode
		{
			get
			{
				return this._PanelCode;
			}
			set
			{
				if ((this._PanelCode != value))
				{
					this.OnPanelCodeChanging(value);
					this.SendPropertyChanging();
					this._PanelCode = value;
					this.SendPropertyChanged("PanelCode");
					this.OnPanelCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHaveHorseLabel", DbType="VarChar(50)")]
		public string IsHaveHorseLabel
		{
			get
			{
				return this._IsHaveHorseLabel;
			}
			set
			{
				if ((this._IsHaveHorseLabel != value))
				{
					this.OnIsHaveHorseLabelChanging(value);
					this.SendPropertyChanging();
					this._IsHaveHorseLabel = value;
					this.SendPropertyChanged("IsHaveHorseLabel");
					this.OnIsHaveHorseLabelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHaveHorseCode", DbType="Int")]
		public System.Nullable<int> IsHaveHorseCode
		{
			get
			{
				return this._IsHaveHorseCode;
			}
			set
			{
				if ((this._IsHaveHorseCode != value))
				{
					this.OnIsHaveHorseCodeChanging(value);
					this.SendPropertyChanging();
					this._IsHaveHorseCode = value;
					this.SendPropertyChanged("IsHaveHorseCode");
					this.OnIsHaveHorseCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessTypeLabel", DbType="VarChar(MAX)")]
		public string BusinessTypeLabel
		{
			get
			{
				return this._BusinessTypeLabel;
			}
			set
			{
				if ((this._BusinessTypeLabel != value))
				{
					this.OnBusinessTypeLabelChanging(value);
					this.SendPropertyChanging();
					this._BusinessTypeLabel = value;
					this.SendPropertyChanged("BusinessTypeLabel");
					this.OnBusinessTypeLabelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessTypeLabelEtc", DbType="VarChar(MAX)")]
		public string BusinessTypeLabelEtc
		{
			get
			{
				return this._BusinessTypeLabelEtc;
			}
			set
			{
				if ((this._BusinessTypeLabelEtc != value))
				{
					this.OnBusinessTypeLabelEtcChanging(value);
					this.SendPropertyChanging();
					this._BusinessTypeLabelEtc = value;
					this.SendPropertyChanged("BusinessTypeLabelEtc");
					this.OnBusinessTypeLabelEtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessTypeCode", DbType="VarChar(100)")]
		public string BusinessTypeCode
		{
			get
			{
				return this._BusinessTypeCode;
			}
			set
			{
				if ((this._BusinessTypeCode != value))
				{
					this.OnBusinessTypeCodeChanging(value);
					this.SendPropertyChanging();
					this._BusinessTypeCode = value;
					this.SendPropertyChanged("BusinessTypeCode");
					this.OnBusinessTypeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PanelName", DbType="VarChar(200)")]
		public string PanelName
		{
			get
			{
				return this._PanelName;
			}
			set
			{
				if ((this._PanelName != value))
				{
					this.OnPanelNameChanging(value);
					this.SendPropertyChanging();
					this._PanelName = value;
					this.SendPropertyChanged("PanelName");
					this.OnPanelNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Owner", DbType="VarChar(100)")]
		public string Owner
		{
			get
			{
				return this._Owner;
			}
			set
			{
				if ((this._Owner != value))
				{
					this.OnOwnerChanging(value);
					this.SendPropertyChanging();
					this._Owner = value;
					this.SendPropertyChanged("Owner");
					this.OnOwnerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(200)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SidoLabel", DbType="VarChar(50)")]
		public string SidoLabel
		{
			get
			{
				return this._SidoLabel;
			}
			set
			{
				if ((this._SidoLabel != value))
				{
					this.OnSidoLabelChanging(value);
					this.SendPropertyChanging();
					this._SidoLabel = value;
					this.SendPropertyChanged("SidoLabel");
					this.OnSidoLabelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SidoCode", DbType="Int")]
		public System.Nullable<int> SidoCode
		{
			get
			{
				return this._SidoCode;
			}
			set
			{
				if ((this._SidoCode != value))
				{
					this.OnSidoCodeChanging(value);
					this.SendPropertyChanging();
					this._SidoCode = value;
					this.SendPropertyChanged("SidoCode");
					this.OnSidoCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SigunguLabel", DbType="VarChar(50)")]
		public string SigunguLabel
		{
			get
			{
				return this._SigunguLabel;
			}
			set
			{
				if ((this._SigunguLabel != value))
				{
					this.OnSigunguLabelChanging(value);
					this.SendPropertyChanging();
					this._SigunguLabel = value;
					this.SendPropertyChanged("SigunguLabel");
					this.OnSigunguLabelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SigunguCode", DbType="Int")]
		public System.Nullable<int> SigunguCode
		{
			get
			{
				return this._SigunguCode;
			}
			set
			{
				if ((this._SigunguCode != value))
				{
					this.OnSigunguCodeChanging(value);
					this.SendPropertyChanging();
					this._SigunguCode = value;
					this.SendPropertyChanged("SigunguCode");
					this.OnSigunguCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DongLabel", DbType="VarChar(50)")]
		public string DongLabel
		{
			get
			{
				return this._DongLabel;
			}
			set
			{
				if ((this._DongLabel != value))
				{
					this.OnDongLabelChanging(value);
					this.SendPropertyChanging();
					this._DongLabel = value;
					this.SendPropertyChanged("DongLabel");
					this.OnDongLabelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailAddress", DbType="VarChar(MAX)")]
		public string DetailAddress
		{
			get
			{
				return this._DetailAddress;
			}
			set
			{
				if ((this._DetailAddress != value))
				{
					this.OnDetailAddressChanging(value);
					this.SendPropertyChanging();
					this._DetailAddress = value;
					this.SendPropertyChanged("DetailAddress");
					this.OnDetailAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone1", DbType="VarChar(50)")]
		public string Phone1
		{
			get
			{
				return this._Phone1;
			}
			set
			{
				if ((this._Phone1 != value))
				{
					this.OnPhone1Changing(value);
					this.SendPropertyChanging();
					this._Phone1 = value;
					this.SendPropertyChanged("Phone1");
					this.OnPhone1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone2", DbType="VarChar(50)")]
		public string Phone2
		{
			get
			{
				return this._Phone2;
			}
			set
			{
				if ((this._Phone2 != value))
				{
					this.OnPhone2Changing(value);
					this.SendPropertyChanging();
					this._Phone2 = value;
					this.SendPropertyChanged("Phone2");
					this.OnPhone2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone3", DbType="VarChar(50)")]
		public string Phone3
		{
			get
			{
				return this._Phone3;
			}
			set
			{
				if ((this._Phone3 != value))
				{
					this.OnPhone3Changing(value);
					this.SendPropertyChanging();
					this._Phone3 = value;
					this.SendPropertyChanged("Phone3");
					this.OnPhone3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone4", DbType="VarChar(50)")]
		public string Phone4
		{
			get
			{
				return this._Phone4;
			}
			set
			{
				if ((this._Phone4 != value))
				{
					this.OnPhone4Changing(value);
					this.SendPropertyChanging();
					this._Phone4 = value;
					this.SendPropertyChanged("Phone4");
					this.OnPhone4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsUpdateCheck", DbType="Int")]
		public System.Nullable<int> IsUpdateCheck
		{
			get
			{
				return this._IsUpdateCheck;
			}
			set
			{
				if ((this._IsUpdateCheck != value))
				{
					this.OnIsUpdateCheckChanging(value);
					this.SendPropertyChanging();
					this._IsUpdateCheck = value;
					this.SendPropertyChanged("IsUpdateCheck");
					this.OnIsUpdateCheckChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.H_Member")]
	public partial class H_Member
	{
		
		private int _idx;
		
		private string _MemberId;
		
		private string _MemberPwd;
		
		private string _MemberPermission;
		
		private string _IsLogic;
		
		private string _MemberName;
		
		public H_Member()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idx", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int idx
		{
			get
			{
				return this._idx;
			}
			set
			{
				if ((this._idx != value))
				{
					this._idx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberId", DbType="VarChar(100)")]
		public string MemberId
		{
			get
			{
				return this._MemberId;
			}
			set
			{
				if ((this._MemberId != value))
				{
					this._MemberId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberPwd", DbType="VarChar(100)")]
		public string MemberPwd
		{
			get
			{
				return this._MemberPwd;
			}
			set
			{
				if ((this._MemberPwd != value))
				{
					this._MemberPwd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberPermission", DbType="VarChar(50)")]
		public string MemberPermission
		{
			get
			{
				return this._MemberPermission;
			}
			set
			{
				if ((this._MemberPermission != value))
				{
					this._MemberPermission = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLogic", DbType="VarChar(50)")]
		public string IsLogic
		{
			get
			{
				return this._IsLogic;
			}
			set
			{
				if ((this._IsLogic != value))
				{
					this._IsLogic = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberName", DbType="VarChar(200)")]
		public string MemberName
		{
			get
			{
				return this._MemberName;
			}
			set
			{
				if ((this._MemberName != value))
				{
					this._MemberName = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
